# December 16, 2022
https://adventofcode.com/2022/day/16

In [5]:
import re
import numpy as np

In [6]:
class Valve:
    num_valves = 0

    def __init__( self, name, flow, neighbors ):
        self.name = name
        self.flow = flow
        self.status = "on" if self.flow == 0 else "off"
        self.neighbors = {nbr:1 for nbr in neighbors}
        self.id = Valve.num_valves
        Valve.num_valves += 1

    def is_on(self):
        return True if self.status == "on" else False

    def turn_on(self):
        if self.is_on:
            return 0
        else:
            self.status = "on"
            return self.flow

    def __lt__(self, other):
        return self.flow < other.flow
    def __eq__(self, other):
        return self.flow == other.flow
    def __le__(self, other):
        return self < other or self == other
    def __str__(self):
        return f'''Valve #{self.id} {self.name} is {self.status}. Flow = {self.flow}. Neighbors: {self.neighbors}'''

    def __repr__(self):
        return str(self)

In [7]:
def parse_map( fn ):
    valves = []

    with open(fn, "r") as file:
        while True:
            line = file.readline().strip("\n")
            if not line: break
            ma = re.match(r'Valve (\w+).*rate=(\d+).*valves? ([\w,\s]*)', line)
            name = ma.group(1)
            flow = int(ma.group(2))
            nbrs = ma.group(3).split(", ")
            valves.append( Valve(name, flow, nbrs) )

    valves.sort(reverse=True)

    return valves


In [8]:
test = parse_map("data/16_test.txt")

In [9]:
print("\n".join([str(x) for x in test]))

Valve #7 HH is off. Flow = 22. Neighbors: {'GG': 1}
Valve #9 JJ is off. Flow = 21. Neighbors: {'II': 1}
Valve #3 DD is off. Flow = 20. Neighbors: {'CC': 1, 'AA': 1, 'EE': 1}
Valve #1 BB is off. Flow = 13. Neighbors: {'CC': 1, 'AA': 1}
Valve #4 EE is off. Flow = 3. Neighbors: {'FF': 1, 'DD': 1}
Valve #2 CC is off. Flow = 2. Neighbors: {'DD': 1, 'BB': 1}
Valve #0 AA is on. Flow = 0. Neighbors: {'DD': 1, 'II': 1, 'BB': 1}
Valve #5 FF is on. Flow = 0. Neighbors: {'EE': 1, 'GG': 1}
Valve #6 GG is on. Flow = 0. Neighbors: {'FF': 1, 'HH': 1}
Valve #8 II is on. Flow = 0. Neighbors: {'AA': 1, 'JJ': 1}


In [10]:
def create_graph( valves ):
    N = len(valves)
    name_map = {v.name:i for i,v in enumerate(valves)}
    dist_array = np.array( [-1]*N*N ).reshape( [N,N])
    for i in range(N):
        dist_array[i,i] = 0

    for cur_id, cur in enumerate(valves):
        dist = 0
        while True:
            # list of valves not reached yet
            tofind = [ i for i,d in enumerate( dist_array[cur_id,:] ) if d == -1 ]
            
            # end state is only the diagonals are 0
            if len(tofind) == 0:
                break
            
            # find most recent neighbors
            cur_nbrs = [ i for i,d in enumerate( dist_array[cur_id,] ) if d == dist ]
            if len(cur_nbrs) == 0:
                # uhoh--- can't get there from here!
                break

            # find neighbors of neighbors that aren't already in the distance array
            next_nbrs = set()
            for d_nbr in cur_nbrs:
                d_nbr_nbr = [ name_map[nbr] for nbr in valves[d_nbr].neighbors if name_map[nbr] in tofind ] 
                next_nbrs = next_nbrs.union( d_nbr_nbr )

            # add the new neighbor to the distance arracy
            dist += 1
            for id in next_nbrs:
                dist_array[cur_id, id] = dist
                dist_array[id, cur_id] = dist

            # end while loop for finding out cur_id distances

    # remove paths that have zero flow other than starting space
    off = [i for i,v in enumerate(valves) if v.flow==0 and v.name != "AA"]
    for i in off[::-1]:
        dist_array = np.delete(dist_array, i, 1)
        dist_array = np.delete(dist_array, i, 0)
        valves = valves[:i] + valves[i+1:]
    
    return dist_array, valves

In [11]:
test_graph, test = create_graph(test)
test_graph

array([[0, 7, 4, 6, 3, 5, 5],
       [7, 0, 3, 3, 4, 4, 2],
       [4, 3, 0, 2, 1, 1, 1],
       [6, 3, 2, 0, 3, 1, 1],
       [3, 4, 1, 3, 0, 2, 2],
       [5, 4, 1, 1, 2, 0, 2],
       [5, 2, 1, 1, 2, 2, 0]])

In [12]:
test

[Valve #7 HH is off. Flow = 22. Neighbors: {'GG': 1},
 Valve #9 JJ is off. Flow = 21. Neighbors: {'II': 1},
 Valve #3 DD is off. Flow = 20. Neighbors: {'CC': 1, 'AA': 1, 'EE': 1},
 Valve #1 BB is off. Flow = 13. Neighbors: {'CC': 1, 'AA': 1},
 Valve #4 EE is off. Flow = 3. Neighbors: {'FF': 1, 'DD': 1},
 Valve #2 CC is off. Flow = 2. Neighbors: {'DD': 1, 'BB': 1},
 Valve #0 AA is on. Flow = 0. Neighbors: {'DD': 1, 'II': 1, 'BB': 1}]

### Part 1

Functions for memoization

In [13]:
def get_key( start, time_left, status ):
    return f'''{start}.{time_left}.{"".join([str(s) for s in status])}'''

def memoize( score, start, time_left, status, best=None ):
    key = get_key(start, time_left, status)
    if best is None:
        best = {key:score}
    else:
        best[key] = score
    return best

def read_memo( start, time_left, status, best=None ):
    if best is None:
        return None
    key = get_key(start, time_left, status)
    if key in best:
        return best[key]
    else:
        return None

In [14]:
def solve_map( valves, graph, start, time_left, status=None, best=None ):
    # convert to status vector to a string so we don't need to copy the whole Valve object
    if status is None:
        status = [ 1 if v.status == "on" else 0 for v in valves ]

    # read memo if possible
    best_result = read_memo( start, time_left, status, best )
    if best_result is not None:
        return best_result

    # Not previously solved. Let's solve it now!
    best_result = 0


    if time_left > 0:
        # possible places we can make it to
        # -- valve is off (s == 0)
        # -- valve is reachable and not current position (dist > 0)
        # -- valve is reachable in time (diat < time_left. We don't use <= since there must be time for an action there.)
        poss = [i for i,s in enumerate(status) if s == 0 and graph[start,i] > 0 and graph[start,i] < time_left]

        # Move to loc and turn on that valve
        for loc in poss:
            new_status = status.copy()
            new_status[loc] = 1
            new_time_left = time_left - graph[start, loc] - 1 # +1 for turning off that valve
            result = valves[loc].flow * new_time_left
            result += solve_map( valves, graph, loc, new_time_left, new_status, best )
            best_result = max(best_result, result)

    best = memoize( best_result, start, time_left, status, best=None )
    return best_result    

In [15]:
### this is wrong now??

solve_map( test, test_graph, 0, 30 )

1408

In [16]:
# 16.7s without memoization
# 8.1 with memoization
puz = parse_map("data/16.txt")
puz_graph, puz = create_graph(puz)
start = [i for i,v in enumerate(puz) if v.name=="AA"][0]
print(f'''Starting at Valve #{start} ({puz[start].name}).''')
solve_map( puz, puz_graph, start, 30 )


Starting at Valve #15 (AA).


2320

### Part 2

In [17]:
def get_key( start1, start2, time_left1, time_left2, status ):
    return f'''{start1}.{start2}.{time_left1}.{time_left2}.{"".join([str(s) for s in status])}'''

def memoize( score, start1, start2, time_left1, time_left2, status, best=None ): 
    key = get_key( start1, start2, time_left1, time_left2, status)

    if best is None:
        best = {key: score}
    else:
        best[key] = score
    return best

def read_memo( start1, start2, time_left1, time_left2, status, best=None ):
    key = get_key( start1, start2, time_left1, time_left2, status)

    if best is not None and key in best:
        best[key]
    else:
        return None

def get_status_cd( status ):
    return sum([ s*(10**i) for i,s in enumerate(status) ])

def get_time_left_cd( tl1, tl2 ):
    return tl1*100 + tl2

def get_start_cd(start1, start2):
    return start1*100 + start2

In [17]:
def solve_map( valves, graph, start1, start2, time_left1, time_left2, status=None, best=None ):
    # convert to status vector to a string so we don't need to copy the whole Valve object
    if status is None:
        status = [ 1 if v.status == "on" else 0 for v in valves ]

    if time_left2 > time_left1:
        # simplify code by making id1 the person with more time left
        tmp = start2
        start2 = start1
        start1 = tmp

        tmp = time_left2
        time_left2 = time_left1
        time_left1 = tmp

    # read memo if possible
    best_result = read_memo( start1, start2, time_left1, time_left2, status, best )
    if best_result is not None:
        return best_result
    
    # Not previously solved. Let's solve it now!
    best_result = 0


    if time_left1 > 0 or time_left2 > 0:
        # possible places we can make it to
        # -- valve is off (s == 0)
        # -- valve is reachable and not current position (dist > 0)
        # -- valve is reachable in time (dist < time_left1. We don't use <= since there must be time for an action there.)
        poss = [i for i,s in enumerate(status) if s == 0 and graph[start1,i] > 0 and graph[start1,i] < time_left1]

        # edge case: person with less time is only one who can turn on an extra valve (ie. it's closer to one)
        if len(poss) == 0:
            result = solve_map(valves, graph, start1, start2, 0, time_left2, status, best)
            best_result = max(best_result, result)
        
        else:
            # Move to loc and turn on that valve
            for loc in poss:
                new_status = status.copy()
                new_status[loc] = 1
                new_time_left1 = time_left1 - graph[start1, loc] - 1 # +1 for turning off that valve
                result = valves[loc].flow * new_time_left1
                result += solve_map( valves, graph, loc, start2, new_time_left1, time_left2, new_status, best )
                best_result = max(best_result, result)
    else:
        global end_count
        end_count += 1
        if end_count % 100000 == 0:
            print(f'''Followed {end_count} chains to the end''')

    # could improve by not memoizing 0s
    best = memoize( best_result, start1, start2, time_left1, time_left2, status, best )

    return best_result    

In [19]:
end_count = 0
solve_map( test, test_graph, 0, 0, 26, 26 )


1707

In [29]:
import sys
puz = parse_map("data/16.txt")
puz_graph = create_graph(puz)
start = [i for i,v in enumerate(puz) if v.name=="AA"][0]
print(f'''Starting at Valve #{start} ({puz[start].name}).''')

is_off = [i for i,v in enumerate(puz) if v.status=="off"]
Noff = len(is_off)
puz_off = np.zeros(Noff*Noff).reshape([Noff, Noff])
for i in range(Noff):
    for j in range(Noff):
        puz_off[i,j] = puz_graph[is_off[i], is_off[j] ]

# Looking for some meaningful structure to help eliminate paths
# Nothing super obvious. Maybe the middle valves tend to be more centrally located
np.set_printoptions(threshold=sys.maxsize)
print(puz_off)

Starting at Valve #14 (AA).
[[ 0. 12.  2.  9.  5. 12.  5.  5. 10. 12. 14.  2.  5.  2.  7.]
 [12.  0. 10.  7.  8.  2.  7.  7.  2.  4.  2. 11. 13. 10.  6.]
 [ 2. 10.  0.  7.  5. 10.  3.  5.  8. 10. 12.  3.  3.  3.  5.]
 [ 9.  7.  7.  0.  4.  5.  4.  5.  5.  3.  9.  7. 10.  8.  2.]
 [ 5.  8.  5.  4.  0.  8.  2.  3.  6.  7. 10.  3.  8.  6.  2.]
 [12.  2. 10.  5.  8.  0.  7.  7.  2.  2.  4. 11. 13. 10.  6.]
 [ 5.  7.  3.  4.  2.  7.  0.  2.  5.  7.  9.  5.  6.  5.  2.]
 [ 5.  7.  5.  5.  3.  7.  2.  0.  5.  8.  9.  6.  8.  3.  3.]
 [10.  2.  8.  5.  6.  2.  5.  5.  0.  3.  4.  9. 11.  8.  4.]
 [12.  4. 10.  3.  7.  2.  7.  8.  3.  0.  6. 10. 13. 11.  5.]
 [14.  2. 12.  9. 10.  4.  9.  9.  4.  6.  0. 13. 15. 12.  8.]
 [ 2. 11.  3.  7.  3. 11.  5.  6.  9. 10. 13.  0.  6.  3.  5.]
 [ 5. 13.  3. 10.  8. 13.  6.  8. 11. 13. 15.  6.  0.  6.  8.]
 [ 2. 10.  3.  8.  6. 10.  5.  3.  8. 11. 12.  3.  6.  0.  6.]
 [ 7.  6.  5.  2.  2.  6.  2.  3.  4.  5.  8.  5.  8.  6.  0.]]


In [38]:
# 61m --- 11714002 end points (3 with tl==26)
# + 624m --- 
end_count = 0
#best = {}
solve_map( puz, puz_graph, start, start, 26, 26, best=best )

Followed 100000 chains to the end
Followed 200000 chains to the end
Followed 300000 chains to the end
Followed 400000 chains to the end
Followed 500000 chains to the end
Followed 600000 chains to the end
Followed 700000 chains to the end
Followed 800000 chains to the end
Followed 900000 chains to the end
Followed 1000000 chains to the end
Followed 1100000 chains to the end
Followed 1200000 chains to the end
Followed 1300000 chains to the end
Followed 1400000 chains to the end
Followed 1500000 chains to the end
Followed 1600000 chains to the end
Followed 1700000 chains to the end
Followed 1800000 chains to the end
Followed 1900000 chains to the end
Followed 2000000 chains to the end
Followed 2100000 chains to the end
Followed 2200000 chains to the end
Followed 2300000 chains to the end
Followed 2400000 chains to the end
Followed 2500000 chains to the end
Followed 2600000 chains to the end
Followed 2700000 chains to the end
Followed 2800000 chains to the end
Followed 2900000 chains to th

KeyboardInterrupt: 

In [39]:
len(best.keys())

18707331

In [40]:
tl = [int(k.split(".")[2]) for k in best.keys()]

In [41]:
sum([1 for x in tl if x ==26])

7

In [32]:
best

{'13.25.0.0.11111111111111111111111111111111111000111111110100011111011': 0,
 '13.25.1.0.11111111111111111111111111111111111000111111110100011111011': 0,
 '25.13.1.1.11111111111111111111111111111111111000111111110100011111011': 0,
 '13.35.0.0.11111111111111111111111110111111111100111111110100011111011': 0,
 '13.35.1.0.11111111111111111111111110111111111100111111110100011111011': 0,
 '13.48.0.0.11111111111111111111111110111111111000111111110110011111011': 0,
 '13.48.1.0.11111111111111111111111110111111111000111111110110011111011': 0,
 '13.56.0.0.11111111111111111111111110111111111000111111110100011111111': 0,
 '13.56.1.0.11111111111111111111111110111111111000111111110100011111111': 0,
 '56.13.1.1.11111111111111111111111110111111111000111111110100011111111': 0,
 '9.13.4.1.11111111111111111111111110111111111000111111110100011111011': 5,
 '25.35.0.0.11111111111110111111111111111111111100111111110100011111011': 0,
 '25.35.2.0.11111111111110111111111111111111111100111111110100011111011': 0,


### Part 2 -- Again
... new strat... try finding the lowest-cost path to the biggest valve
but that didn't turn out to be very helpful

Thoughts:
1. If you're going to turn on a valve, the best time to do it is when you're already there.
2. If you will turn on a valve, do it the first time you visit. The cost is the same, but the benefit is greater.
  * Turns out this is FALSE. There is extra cost in the form of delaying turning on other valves, possibly HUGE ones.
3. 



In [75]:
test

[Valve #0 AA is on. Flow = 0. Neighbors: {'DD': 1, 'II': 1, 'BB': 1},
 Valve #1 BB is off. Flow = 13. Neighbors: {'CC': 1, 'AA': 1},
 Valve #2 CC is off. Flow = 2. Neighbors: {'DD': 1, 'BB': 1},
 Valve #3 DD is off. Flow = 20. Neighbors: {'CC': 1, 'AA': 1, 'EE': 1},
 Valve #4 EE is off. Flow = 3. Neighbors: {'FF': 1, 'DD': 1},
 Valve #7 HH is off. Flow = 22. Neighbors: {'GG': 1},
 Valve #9 JJ is off. Flow = 21. Neighbors: {'II': 1}]

In [76]:
test_graph

array([[0, 1, 2, 1, 2, 5, 2],
       [1, 0, 1, 2, 3, 6, 3],
       [2, 1, 0, 1, 2, 5, 4],
       [1, 2, 1, 0, 1, 4, 3],
       [2, 3, 2, 1, 0, 3, 4],
       [5, 6, 5, 4, 3, 0, 7],
       [2, 3, 4, 3, 4, 7, 0]])

In [135]:
def find_biggest_valve( valves ):
    best_val = 0
    for i, valve in enumerate(valves):
        if valve.flow > best_val:
            best_i = i
            best_val = valve.flow

    return best_i

def midpoint_cost( valves, graph, time_left, start, mid, end ):
    # additional cost of going to start to end via mid and turning on that valve
    # indirect time includes one unit to turn on mid valve
    indirect_time = min(time_left, graph[start][mid] + graph[mid][end] + 1 )
    direct_time = min(time_left, graph[start][end])

    # we miss out on some flow from the end valve
    extra_cost = (indirect_time - direct_time) * valves[end].flow

    # but get additional flow from the mid valve
    bonus_flow_time = max(0, indirect_time - (graph[start][mid] + 1))
    bonus_flow = bonus_flow_time * valves[mid].flow
    return extra_cost - bonus_flow, indirect_time - direct_time

def midpoint_flow( valves, graph, time_left, start, mid, end ):
    # extra flow achieved by going start -> mid -> end and turning both valves on

    # Time for mid valve and end valve to flow
    mid_flow_time = max(time_left - graph[start][mid] - 1, 0)
    end_flow_time = max(time_left - graph[start][mid] - 1 - graph[mid][end] - 1, 0)
    # Flow time for end valve if go straight there
    direct_flow_time = max(time_left - graph[start][end] - 1, 0)
    # Extra time to stop and turn on mid
    lost_time = end_flow_time - direct_flow_time 
    # Extra flow is the flow from mid - the lost flow from end for taking extra time to get there
    extra_flow = mid_flow_time * valves[mid].flow - lost_time * valves[end].flow 
    
    return extra_flow, lost_time

In [129]:
time_left = 26
valves = test
graph = test_graph
start = 0
end = find_biggest_valve( valves )
# every minute of delay reduces flow by this amount

status = [0] * len(valves)
best_cost = 0
best_i = end

def paths_to_try( valves, graph, time_left, status, cur, end ):
    # Get all valid paths from cur to end
    # A path is valid if it's direct or it produces more flow
    # More flow is not necessarily better since it costs more time
    # But direct is better than any path with less flow
    # Note: We are not comparing against paths that do attempt to reach end

    # List of valid paths so far (excluding end)
    paths = [ [start] ] 

    # amount of flow generated by using this path for duration of time_left
    flows = [ (time_left - graph[start][end] - 1)*valves[end].flow ]
    
    # time for paths from start, but excluding end
    times = [0]

    id = 0
    while id < len(paths):
        cur = paths[id]

        # see if we could add another step to the path
        for i in range(len(valves)):
            # this valve is already on path, or else the valve is off
            if i == start or i == end or i in cur or status[i] == 1:
                continue

            # consider stopping at i en route to end.
            # add to paths if it's possibly better than going from current path straight to end
            extra_flow, lost_time = midpoint_flow( valves, graph, time_left - times[id], cur[-1], i, end)
            if extra_flow > 0:
                print( cur, i, extra_flow)
                paths.append( cur + [i] )
                flows.append( flows[id] + extra_flow )
                times.append( times[id] + lost_time )
        id += 1
    return paths, 

best_cost = 1
best_i = []
for i, cost in enumerate(costs):
    if cost < best_cost:
        best_i = [i]
        best_cost = cost
    elif cost == best_cost and set():
        best_i.append(i)




Target: 5
0
1
0 1 5
[0] 1 -12
2
0 2 5
3
0 3 5
[0] 3 -58
4
0 4 5
5
6
0 6 5
[0] 6 -37
0
1
2
1 2 5
3
1 3 5
[0, 1] 3 -58
4
1 4 5
5
6
1 6 5
[0, 1] 6 -37
0
1
3 1 5
2
3 2 5
3
4
3 4 5
5
6
3 6 5
0
1
6 1 5
[0, 6] 1 -12
2
6 2 5
3
6 3 5
[0, 6] 3 -58
4
6 4 5
5
6
0
1
2
3 2 5
3
4
3 4 5
5
6
3 6 5
0
1
2
6 2 5
3
6 3 5
[0, 1, 6] 3 -58
4
6 4 5
5
6
0
1
2
1 2 5
3
1 3 5
[0, 6, 1] 3 -58
4
1 4 5
5
6
0
1
3 1 5
2
3 2 5
3
4
3 4 5
5
6
0
1
2
3 2 5
3
4
3 4 5
5
6
0
1
2
3 2 5
3
4
3 4 5
5
6


In [133]:
set([1,4,3]) == set([3,4,2])

False

In [109]:
paths

[[0],
 [0, 1],
 [0, 3],
 [0, 6],
 [0, 1, 3],
 [0, 1, 6],
 [0, 6, 1],
 [0, 6, 3],
 [0, 1, 6, 3],
 [0, 6, 1, 3]]

In [110]:
costs

[0, -12, -58, -37, -83, -62, -70, -116, -154, -162]

In [130]:
costs

[0, -12, -58, -37, -83, -114, -112, -116, -206, -204]

In [131]:
[
    6*13 - 3*22,
    4*20 - 22,
    7*21 - 5*22,
    7*13 + 4*20 - 4*22,
    11*13 + 7*21 - 8*22,
    10*21 + 6*13 - 8*22,
    
]

[12, 58, 37, 83, 114, 112]

In [95]:
test_graph

array([[0, 1, 2, 1, 2, 5, 2],
       [1, 0, 1, 2, 3, 6, 3],
       [2, 1, 0, 1, 2, 5, 4],
       [1, 2, 1, 0, 1, 4, 3],
       [2, 3, 2, 1, 0, 3, 4],
       [5, 6, 5, 4, 3, 0, 7],
       [2, 3, 4, 3, 4, 7, 0]])

In [114]:
midpoint_cost( valves, graph, 32, 0, 6, 5)

10 5 110 7 147


-37

In [101]:
(3+2+4+2)*21 + (2+4+1)*13 + 4*20 - (14-5)*22

204

In [103]:
midpoint_cost(valves, graph, 32, 0, 1, 5)

-12

In [104]:
test_graph

array([[0, 1, 2, 1, 2, 5, 2],
       [1, 0, 1, 2, 3, 6, 3],
       [2, 1, 0, 1, 2, 5, 4],
       [1, 2, 1, 0, 1, 4, 3],
       [2, 3, 2, 1, 0, 3, 4],
       [5, 6, 5, 4, 3, 0, 7],
       [2, 3, 4, 3, 4, 7, 0]])

In [106]:
(3+3+4)*13 + (7*21) + 4*20 - 9*22

159

In [18]:
test

[Valve #0 AA is on. Flow = 0. Neighbors: {'DD': 1, 'II': 1, 'BB': 1},
 Valve #1 BB is off. Flow = 13. Neighbors: {'CC': 1, 'AA': 1},
 Valve #2 CC is off. Flow = 2. Neighbors: {'DD': 1, 'BB': 1},
 Valve #3 DD is off. Flow = 20. Neighbors: {'CC': 1, 'AA': 1, 'EE': 1},
 Valve #4 EE is off. Flow = 3. Neighbors: {'FF': 1, 'DD': 1},
 Valve #5 FF is on. Flow = 0. Neighbors: {'EE': 1, 'GG': 1},
 Valve #6 GG is on. Flow = 0. Neighbors: {'FF': 1, 'HH': 1},
 Valve #7 HH is off. Flow = 22. Neighbors: {'GG': 1},
 Valve #8 II is on. Flow = 0. Neighbors: {'AA': 1, 'JJ': 1},
 Valve #9 JJ is off. Flow = 21. Neighbors: {'II': 1}]

### Part 2 -- Third attempt
Let's try an A* type deal and avoid exploring paths that we know won't win

# Too low 2134, 2493, 2714
# Too high 3000

In [18]:
from queue import PriorityQueue

In [19]:
class Strat:
    next_id = 0

    def __init__(self, phum, pele, thum, tele, score, prio=0, tarrh=[], tarre=[] ):
        self.id = Strat.next_id
        Strat.next_id += 1

        # paths for human and elephant
        self.phum = phum
        self.pele = pele

        # time left for them
        self.thum = thum
        self.tele = tele

        self.score = score
        self.prio = prio

        # These are arrays of the time_left values at each point along path
        # Not necessary, but it helped me debug
        self.tarrh = tarrh
        self.tarre = tarre

        return

    # Note: for our purpose < means has higher priority
    def __lt__(self, other):
        return self.prio > other.prio

    def __eq__(self, other):
        # Must have same score
        if self.score != other.score:
            return False

        # With actors in same position at same time, possibly swapped though
        if not (
            (self.phum[-1] == other.phum[-1] and self.thum == other.thum
                and self.pele[-1] == other.pele[-1] and self.tele == other.tele)
            or 
            (self.phum[-1] == other.pele[-1] and self.thum == other.tele
                and self.pele[-1] == other.phum[-1] and self.tele == other.thum)
        ):
            return False

        # and the same valves must be on
        on1 = set( self.phum + self.pele )
        on2 = set( other.phum + other.pele )
        if on1 != on2:
            return False
        
        # in that case, previous history is immaterial
        return True



In [20]:
def get_nbr( strat, graph ):
    '''return valves we might check'''
    # We assume starting valve has flow 0
    return [i for i in range(graph.shape[0]) if i not in strat.phum and i not in strat.pele]


In [21]:
def calc_time_left( path, cur_time, nbr, graph ):
    cur = path[-1]
    dist = graph[cur][nbr]

    # time left after reaching valve and turning it on, or 0 if you can't make it
    return max(0, cur_time - dist - 1)

def heuristic1( strat, valves, graph ):
    '''An upper bound assuming all valves are 1 unit away from each other'''
    # Assume valves are sorted
    valves_left = get_nbr( strat, graph )
    flows = [valves[id].flow for id in valves_left]
    
    # Upper bound assumes all valves are 1 unit away from each other
    # we can improve on this upper bound if needed
    ub = 0
    t1 = strat.thum
    t2 = strat.tele
    for f in flows:
        if t1 < t2 and t2 > 2:
            ub += (t2-2)*f
            t2 -= 2
        elif t1 > 2:
            ub += (t1-2)*f
            t1 -= 2
        else:
            # no more time to turn stuff on
            break

    return ub

def heuristic( strat, valves, graph ):
    '''an upper bound assuming that you and ele can simultaneously go toward all remaining valves'''
    # Assume valves are sorted
    valves_left = get_nbr( strat, graph )
    flows = [valves[id].flow for id in valves_left]
    
    curh = strat.phum[-1]
    cure = strat.pele[-1]
    tlh = strat.thum
    tle = strat.tele

    flow = [ valves[v].flow * max(0, tlh - graph[curh][v], tle - graph[cure][v]) for v in valves_left ]
    return sum(flow) 




In [22]:
import datetime as dt

In [96]:
def this_could_be_it( valves, graph, start, time ):
    
    # Heuristic will be max possible flow
    # Priority will be negated to sort from high to low 
    frontier = PriorityQueue()

    #   hum path, ele path, hum time, ele time, score
    start = Strat( [start], [start], time, time, 0, 0, [time], [time] )
    frontier.put( start )

    # track which ones we've already investigated
    seen = [start]
    best_strat = start
    best_score = -1
    nbest = 1
    
    while not frontier.empty():
        cur = frontier.get()

        # this strat can't possibly win, skip it
        # remember prio is negative of the upper bound on this strats final score
        if cur.prio <= best_score:
            continue

        neighbors = get_nbr(cur, graph)
        for nbr in neighbors:
            
            h_time_left = calc_time_left( cur.phum, cur.thum, nbr, graph )
            e_time_left = calc_time_left( cur.pele, cur.tele, nbr, graph )

            # I'm not 100% sure this works, but it will lead to heuristics that aren't so crazy inflated.
            # This led quickly to a wrong answer of 2714 in ~43s

            # On second thought this makes sense. Even if human ultimately goes to nbr,
            # We can move the ele to its next destination first...
            # Eventually ele will use up its extra time
            # Maybe the bug earlier was because I had a strict inequality here?
            
            try_hum = h_time_left >= e_time_left
            try_ele = e_time_left >= h_time_left and (cur.pele[-1] != cur.phum[-1] or cur.tele != cur.thum)

            # better condition, if ele has time to turn on valve and return to spot, then no point in human doing it
            # WHOOPS... the problem with this is it forces the elephant away from a possibly more efficient position... maybe?
            # not sure, but I got the wrong answer of 2714 again
            #try_hum = (h_time_left > e_time_left - graph[nbr][cur.pele[-1]])
            #try_ele = (e_time_left > h_time_left - graph[nbr][cur.phum[-1]]
            #            and (cur.pele[-1] != cur.phum[-1] or cur.tele != cur.thum))

            # This MUST be okay... if both human and ele are in same spot at same time, it doesn't matter who moves
            #try_hum = True
            #try_ele = (cur.pele[-1] != cur.phum[-1] or cur.pele[-1] != cur.phum[-1])

            # Try Human...
            if try_hum:
                time_left = h_time_left
                new_score = cur.score + time_left * valves[nbr].flow # time_left = time when valve is opened, it starts flowing next minute

                new_strat = Strat( [*cur.phum, nbr], cur.pele, time_left, cur.tele, new_score, 0, [*cur.tarrh, time_left], cur.tarre )
                if True:#new_strat not in seen:
                    if new_score > best_score:
                        nbest += 1
                        print(f"Best [{nbest}]: {new_score}")
                        print(dt.datetime.now().isoformat())
                        best_score = new_score
                        best_strat = new_strat
                    heur = heuristic( new_strat, valves, graph )
                    prio = new_score + heur
                    new_strat.prio = prio
                    #seen.append( new_strat )

                # don't bother queuing this new strat unless it could top the best score
                # Note: if this is the current best_score, it means we only add if there's time to turn on more valves
                if prio > best_score:
                    frontier.put( new_strat )

            # Try Elephant...
            if try_ele:
                time_left = e_time_left
                new_score = cur.score + time_left * valves[nbr].flow # time_left = time for this valve to flow
                new_strat = Strat( cur.phum, [*cur.pele, nbr], cur.thum, time_left, new_score, 0, cur.tarrh, [*cur.tarre, time_left] )

                if True:#new_strat not in seen:
                    if new_score > best_score:
                        nbest += 1
                        print(f"Best [{nbest}]: {new_score}")
                        print(dt.datetime.now().isoformat())
                        best_score = new_score
                        best_strat = new_strat
                    heur = heuristic( new_strat, valves, graph )
                    prio = new_score + heur
                    new_strat.prio = prio
                    #seen.append(new_strat)

                # don't bother queuing this new strat unless it could top the best score
                # Note: if this is the current best_score, it means we only add if there's time to turn on more valves
                if prio > best_score:
                    frontier.put( new_strat )

    # no more strats to check out
    return best_score, best_strat

            



        



In [97]:
start = [i for i,v in enumerate(test) if v.name == "AA"][0]
score, strat = this_could_be_it( test, test_graph, start, 26)
print(score)

Best [2]: 440
2022-12-25T13:53:41.568732
Best [3]: 483
2022-12-25T13:53:41.568732
Best [4]: 486
2022-12-25T13:53:41.569726
Best [5]: 529
2022-12-25T13:53:41.569726
Best [6]: 552
2022-12-25T13:53:41.569726
Best [7]: 752
2022-12-25T13:53:41.569726
Best [8]: 795
2022-12-25T13:53:41.569726
Best [9]: 920
2022-12-25T13:53:41.570725
Best [10]: 963
2022-12-25T13:53:41.570725
Best [11]: 1381
2022-12-25T13:53:41.570725
Best [12]: 1630
2022-12-25T13:53:41.571725
Best [13]: 1674
2022-12-25T13:53:41.573723
Best [14]: 1675
2022-12-25T13:53:41.576728
Best [15]: 1707
2022-12-25T13:53:41.576728
1707


In [25]:
print([test[x].name for x in strat.phum])
print([test[x].name for x in strat.pele])
print(strat.thum)
print(strat.tele)

['AA', 'DD', 'HH', 'EE']
['AA', 'JJ', 'BB', 'CC']
15
17


In [39]:
def score_strat( strat, valves, graph, time=26, hum=1 ):
    if hum == 1:
        n1 = "You turn"
        n2 = "Ele turns"
    else:
        n1 = "Ele turns"
        n2 = "You turn"
    
    tl1 = tl2 = time
    i1 = i2 = 0
    fpt = 0
    total_flow = 0
    while tl1 > 0 or tl2 > 0:
        print(i1, i2)
        if i1 < len(strat.phum) - 1:
            tl1b = tl1 - (graph[ strat.phum[i1] ][ strat.phum[i1+1] ] + 1)
        else:
            tl1b = 0
        if i2 < len(strat.pele) - 1:
            tl2b = tl2 - (graph[ strat.pele[i2] ][ strat.pele[i2+1] ] + 1)
        else:
            tl2b = 0
        if tl1b == tl2b == 0:
            break
        
        if tl1b >= tl2b:
            i1 += 1
            tl1 = tl1b
            v = valves[ strat.phum[i1] ]
            fpt += v.flow
            total_flow += (tl1)*v.flow
            print(f"@{time-tl1} {n1} on Valve {v.name} releasing {v.flow} and increasing FPT to {fpt}.")
            print("Total =", total_flow)
        else:
            i2 += 1
            tl2 = tl2b
            v = valves[ strat.pele[i2] ]
            fpt += v.flow
            total_flow += (tl2)*v.flow
            print(f"@{time-tl2} {n2} on Valve {v.name} releasing {v.flow} and increasing FPT to {fpt}.")
            print("Total =", total_flow)

    return total_flow


    

In [209]:
score_strat( strat, test, test_graph, time=26, hum=1 )


0 0
@2 Ele turns on Valve DD releasing 20 and increasing FPT to 20.
Total = 480
0 1
@3 You turn on Valve JJ releasing 21 and increasing FPT to 41.
Total = 963
1 1
@7 You turn on Valve BB releasing 13 and increasing FPT to 54.
Total = 1210
2 1
@7 Ele turns on Valve HH releasing 22 and increasing FPT to 76.
Total = 1628
2 2
@9 You turn on Valve CC releasing 2 and increasing FPT to 78.
Total = 1662
3 2
@11 Ele turns on Valve EE releasing 3 and increasing FPT to 81.
Total = 1707
3 3


1707

In [27]:
def print_strat( strat, valves ):
    print( "One:",  [f"{valves[ strat.phum[i] ].name} @{26 - strat.tarrh[i]}" for i in range(len(strat.phum))])
    print( "Two:",[f"{valves[ strat.pele[i] ].name} @{26 - strat.tarre[i]}" for i in range(len(strat.pele))])

In [28]:
print_strat(strat, test)

One: ['AA @0', 'DD @2', 'HH @7', 'EE @11']
Two: ['AA @0', 'JJ @3', 'BB @7', 'CC @9']


In [30]:
print([f"{v.name}: {v.flow}" for v in test])
test_graph

['HH: 22', 'JJ: 21', 'DD: 20', 'BB: 13', 'EE: 3', 'CC: 2', 'AA: 0']


array([[0, 7, 4, 6, 3, 5, 5],
       [7, 0, 3, 3, 4, 4, 2],
       [4, 3, 0, 2, 1, 1, 1],
       [6, 3, 2, 0, 3, 1, 1],
       [3, 4, 1, 3, 0, 2, 2],
       [5, 4, 1, 1, 2, 0, 2],
       [5, 2, 1, 1, 2, 2, 0]])

In [57]:
puz = parse_map("data/16.txt")
puz_graph, puz = create_graph(puz)

In [98]:
# The h_time_left <= e_time_left shortcut, which I now believe is good but with prio shortcut turned off
# LMFAO! I had the wrong starting tile this entire time.... *sigh*
start = len(puz)-1
score, strat = this_could_be_it( puz, puz_graph, start, 26)
print(score)

Best [2]: 450
2022-12-25T13:53:50.036087
Best [3]: 480
2022-12-25T13:53:50.037093
Best [4]: 529
2022-12-25T13:53:50.037093
Best [5]: 549
2022-12-25T13:53:50.038140
Best [6]: 598
2022-12-25T13:53:50.038140
Best [7]: 639
2022-12-25T13:53:50.039087
Best [8]: 662
2022-12-25T13:53:50.040088
Best [9]: 678
2022-12-25T13:53:50.040088
Best [10]: 727
2022-12-25T13:53:50.040088
Best [11]: 757
2022-12-25T13:53:50.042086
Best [12]: 774
2022-12-25T13:53:50.043085
Best [13]: 823
2022-12-25T13:53:50.044086
Best [14]: 865
2022-12-25T13:53:50.045089
Best [15]: 886
2022-12-25T13:53:50.046089
Best [16]: 925
2022-12-25T13:53:50.047091
Best [17]: 979
2022-12-25T13:53:50.050087
Best [18]: 1009
2022-12-25T13:53:50.050087
Best [19]: 1023
2022-12-25T13:53:50.052140
Best [20]: 1054
2022-12-25T13:53:50.053152
Best [21]: 1095
2022-12-25T13:53:50.054140
Best [22]: 1102
2022-12-25T13:53:50.056086
Best [23]: 1183
2022-12-25T13:53:50.056086
Best [24]: 1363
2022-12-25T13:53:50.058088
Best [25]: 1703
2022-12-25T13:53:50

In [71]:
# The h_time_left <= e_time_left shortcut, which I now believe is good
# gets 2714 in ~43s
score, strat = this_could_be_it( puz, puz_graph, start, 26)
print(score)

Best [2]: 350
2022-12-25T13:42:30.658777
Best [3]: 504
2022-12-25T13:42:30.659777
Best [4]: 529
2022-12-25T13:42:30.659777
Best [5]: 561
2022-12-25T13:42:30.661774
Best [6]: 586
2022-12-25T13:42:30.661774
Best [7]: 594
2022-12-25T13:42:30.662774
Best [8]: 619
2022-12-25T13:42:30.662774
Best [9]: 634
2022-12-25T13:42:30.663774
Best [10]: 666
2022-12-25T13:42:30.664778
Best [11]: 691
2022-12-25T13:42:30.664778
Best [12]: 709
2022-12-25T13:42:30.667774
Best [13]: 826
2022-12-25T13:42:30.668776
Best [14]: 851
2022-12-25T13:42:30.668776
Best [15]: 853
2022-12-25T13:42:30.669777
Best [16]: 964
2022-12-25T13:42:30.670777
Best [17]: 989
2022-12-25T13:42:30.671780
Best [18]: 1033
2022-12-25T13:42:30.672796
Best [19]: 1314
2022-12-25T13:42:30.675829
Best [20]: 1445
2022-12-25T13:42:30.675829
Best [21]: 1656
2022-12-25T13:42:30.678774
Best [22]: 1691
2022-12-25T13:42:30.678774
Best [23]: 1699
2022-12-25T13:42:30.684777
Best [24]: 1887
2022-12-25T13:42:30.756804
Best [25]: 1900
2022-12-25T13:42:30

In [58]:
# The only shortcut here is if human and ele are in same spot at same time, we only try moving one of them
# it gives wrong answer of 2714 in 13'48"
score, strat = this_could_be_it( puz, puz_graph, start, 26)
print(score)

Best [2]: 350
2022-12-25T12:44:22.375911
Best [3]: 504
2022-12-25T12:44:22.375911
Best [4]: 529
2022-12-25T12:44:22.375911
Best [5]: 561
2022-12-25T12:44:22.377912
Best [6]: 586
2022-12-25T12:44:22.377912
Best [7]: 594
2022-12-25T12:44:22.379911
Best [8]: 619
2022-12-25T12:44:22.379911
Best [9]: 634
2022-12-25T12:44:22.382911
Best [10]: 666
2022-12-25T12:44:22.383912
Best [11]: 691
2022-12-25T12:44:22.383912
Best [12]: 709
2022-12-25T12:44:22.387911
Best [13]: 802
2022-12-25T12:44:22.388911
Best [14]: 826
2022-12-25T12:44:22.388911
Best [15]: 851
2022-12-25T12:44:22.388911
Best [16]: 853
2022-12-25T12:44:22.394911
Best [17]: 964
2022-12-25T12:44:22.396945
Best [18]: 989
2022-12-25T12:44:22.396945
Best [19]: 1033
2022-12-25T12:44:22.399970
Best [20]: 1087
2022-12-25T12:44:22.410911
Best [21]: 1118
2022-12-25T12:44:22.418910
Best [22]: 1131
2022-12-25T12:44:22.426910
Best [23]: 1186
2022-12-25T12:44:22.433912
Best [24]: 1201
2022-12-25T12:44:22.443958
Best [25]: 1289
2022-12-25T12:44:22.

In [36]:
# This one had condition where if ele can turn on valve and return to its spot, then no need for human to move
# it gives the wrong answer of 2714 in 13'22"
score, strat = this_could_be_it( puz, puz_graph, start, 26)
print(score)

Best [2]: 350
2022-12-25T11:23:55.603423
Best [3]: 504
2022-12-25T11:23:55.603423
Best [4]: 529
2022-12-25T11:23:55.603423
Best [5]: 561
2022-12-25T11:23:55.606420
Best [6]: 586
2022-12-25T11:23:55.606420
Best [7]: 594
2022-12-25T11:23:55.607420
Best [8]: 619
2022-12-25T11:23:55.607420
Best [9]: 634
2022-12-25T11:23:55.610426
Best [10]: 666
2022-12-25T11:23:55.611420
Best [11]: 691
2022-12-25T11:23:55.611420
Best [12]: 709
2022-12-25T11:23:55.614425
Best [13]: 802
2022-12-25T11:23:55.615424
Best [14]: 826
2022-12-25T11:23:55.615424
Best [15]: 851
2022-12-25T11:23:55.615424
Best [16]: 853
2022-12-25T11:23:55.621425
Best [17]: 964
2022-12-25T11:23:55.622421
Best [18]: 989
2022-12-25T11:23:55.622421
Best [19]: 1033
2022-12-25T11:23:55.626425
Best [20]: 1087
2022-12-25T11:23:55.637425
Best [21]: 1118
2022-12-25T11:23:55.644419
Best [22]: 1131
2022-12-25T11:23:55.652419
Best [23]: 1186
2022-12-25T11:23:55.660418
Best [24]: 1201
2022-12-25T11:23:55.668932
Best [25]: 1289
2022-12-25T11:23:55.

In [242]:
score, strat = this_could_be_it( puz, puz_graph, start, 26)
print(score)

Best [2]: 350
2022-12-25T01:19:03.176982
Best [3]: 504
2022-12-25T01:19:03.177985
Best [4]: 529
2022-12-25T01:19:03.177985
Best [5]: 561
2022-12-25T01:19:03.181983
Best [6]: 586
2022-12-25T01:19:03.181983
Best [7]: 594
2022-12-25T01:19:03.186983
Best [8]: 619
2022-12-25T01:19:03.186983
Best [9]: 634
2022-12-25T01:19:03.195985
Best [10]: 666
2022-12-25T01:19:03.201982
Best [11]: 691
2022-12-25T01:19:03.202984
Best [12]: 709
2022-12-25T01:19:03.213982
Best [13]: 802
2022-12-25T01:19:03.224036
Best [14]: 826
2022-12-25T01:19:03.224036
Best [15]: 851
2022-12-25T01:19:03.224036
Best [16]: 853
2022-12-25T01:19:03.233983
Best [17]: 964
2022-12-25T01:19:03.249046
Best [18]: 989
2022-12-25T01:19:03.249046
Best [19]: 1033
2022-12-25T01:19:03.262983
Best [20]: 1087
2022-12-25T01:19:03.307983
Best [21]: 1118
2022-12-25T01:19:03.328988
Best [22]: 1131
2022-12-25T01:19:03.362983
Best [23]: 1186
2022-12-25T01:19:03.398988
Best [24]: 1201
2022-12-25T01:19:03.442035
Best [25]: 1289
2022-12-25T01:19:03.

KeyboardInterrupt: 

In [251]:
# I forget what I added here, but it took too long anyway
score, strat = this_could_be_it( puz, puz_graph, start, 26)
print(score)

Best [2]: 350
2022-12-25T01:46:40.153162
Best [3]: 504
2022-12-25T01:46:40.154162
Best [4]: 529
2022-12-25T01:46:40.154162
Best [5]: 561
2022-12-25T01:46:40.159162
Best [6]: 586
2022-12-25T01:46:40.160161
Best [7]: 594
2022-12-25T01:46:40.167163
Best [8]: 619
2022-12-25T01:46:40.168163
Best [9]: 634
2022-12-25T01:46:40.175162
Best [10]: 666
2022-12-25T01:46:40.182163
Best [11]: 691
2022-12-25T01:46:40.182163
Best [12]: 709
2022-12-25T01:46:40.202163
Best [13]: 802
2022-12-25T01:46:40.212163
Best [14]: 826
2022-12-25T01:46:40.213163
Best [15]: 851
2022-12-25T01:46:40.214164
Best [16]: 853
2022-12-25T01:46:40.235975
Best [17]: 964
2022-12-25T01:46:40.253976
Best [18]: 989
2022-12-25T01:46:40.254976
Best [19]: 1033
2022-12-25T01:46:40.275976
Best [20]: 1087
2022-12-25T01:46:40.325513
Best [21]: 1118
2022-12-25T01:46:40.358746
Best [22]: 1131
2022-12-25T01:46:40.409960
Best [23]: 1186
2022-12-25T01:46:40.446015
Best [24]: 1201
2022-12-25T01:46:40.493013
Best [25]: 1289
2022-12-25T01:46:40.

: 

In [220]:
print_strat(strat, puz)

One: ['HF @0', 'CF @3', 'XJ @10', 'DP @14']
Two: ['HF @0', 'DY @3', 'KG @13', 'EF @16']


In [226]:
strat.phum, strat.tarrh, strat.pele, strat.pele

([6, 4, 1, 5], [26, 23, 16, 12], [6, 2, 0, 3], [6, 2, 0, 3])

In [225]:
get_nbr(strat,puz)

[]

In [ ]:
strat

In [217]:
print([f"{v.name}: {v.flow}" for v in puz])
puz_graph

['KG: 25', 'XJ: 24', 'DY: 23', 'EF: 22', 'CF: 20', 'DP: 18', 'HF: 17', 'RU: 16', 'RC: 14', 'AH: 12', 'XE: 11', 'VQ: 9', 'OY: 7', 'WE: 5', 'VG: 3', 'AA: 0']


array([[ 0, 10,  9,  2, 13,  7, 11,  3, 11,  3,  6,  6,  3,  5,  5,  7],
       [10,  0,  3, 12,  6,  3,  4,  7,  2, 10, 13,  8, 11,  7,  5,  5],
       [ 9,  3,  0, 10,  4,  5,  2,  6,  2,  8, 11,  5,  8,  5,  4,  2],
       [ 2, 12, 10,  0, 14,  9, 12,  5, 12,  2,  5,  5,  2,  5,  7,  8],
       [13,  6,  4, 14,  0,  9,  2, 10,  4, 12, 15,  9, 12,  9,  8,  6],
       [ 7,  3,  5,  9,  9,  0,  7,  4,  5,  7, 10,  5,  8,  4,  2,  3],
       [11,  4,  2, 12,  2,  7,  0,  8,  2, 10, 13,  7, 10,  7,  6,  4],
       [ 3,  7,  6,  5, 10,  4,  8,  0,  8,  5,  8,  3,  6,  2,  2,  4],
       [11,  2,  2, 12,  4,  5,  2,  8,  0, 10, 13,  7, 10,  7,  6,  4],
       [ 3, 10,  8,  2, 12,  7, 10,  5, 10,  0,  3,  5,  3,  3,  5,  6],
       [ 6, 13, 11,  5, 15, 10, 13,  8, 13,  3,  0,  8,  6,  6,  8,  9],
       [ 6,  8,  5,  5,  9,  5,  7,  3,  7,  5,  8,  0,  3,  2,  3,  3],
       [ 3, 11,  8,  2, 12,  8, 10,  6, 10,  3,  6,  3,  0,  5,  6,  6],
       [ 5,  7,  5,  5,  9,  4,  7,  2,  7,  3,  6,

In [61]:
#long_strat = strat
#long_score = score
print_strat(long_strat, puz)

One: ['HF @0', 'CF @3', 'RC @8', 'XJ @11', 'DP @15', 'VG @18', 'WE @21', 'VQ @24']
Two: ['HF @0', 'DY @3', 'RU @10', 'KG @14', 'EF @17', 'AH @20', 'XE @24']


In [73]:
#fast_strat = strat
#fast_score = score
print_strat(fast_strat, puz)

One: ['HF @0', 'DY @3', 'RU @10', 'KG @14', 'EF @17', 'AH @20', 'XE @24']
Two: ['HF @0', 'CF @3', 'RC @8', 'XJ @11', 'DP @15', 'VG @18', 'WE @21', 'VQ @24']


In [74]:
score_strat( fast_strat, puz, puz_graph )

0 0
@3 You turn on Valve DY releasing 23 and increasing FPT to 23.
Total = 529
1 0
@3 Ele turns on Valve CF releasing 20 and increasing FPT to 43.
Total = 989
1 1
@8 Ele turns on Valve RC releasing 14 and increasing FPT to 57.
Total = 1241
1 2
@10 You turn on Valve RU releasing 16 and increasing FPT to 73.
Total = 1497
2 2
@11 Ele turns on Valve XJ releasing 24 and increasing FPT to 97.
Total = 1857
2 3
@14 You turn on Valve KG releasing 25 and increasing FPT to 122.
Total = 2157
3 3
@15 Ele turns on Valve DP releasing 18 and increasing FPT to 140.
Total = 2355
3 4
@17 You turn on Valve EF releasing 22 and increasing FPT to 162.
Total = 2553
4 4
@18 Ele turns on Valve VG releasing 3 and increasing FPT to 165.
Total = 2577
4 5
@20 You turn on Valve AH releasing 12 and increasing FPT to 177.
Total = 2649
5 5
@21 Ele turns on Valve WE releasing 5 and increasing FPT to 182.
Total = 2674
5 6
@24 You turn on Valve XE releasing 11 and increasing FPT to 193.
Total = 2696
6 6
@24 Ele turns on V

2714

In [88]:
strat.phum, strat.thum, strat.tarrh

([6, 2, 7, 0, 3, 9, 10], 2, [26, 23, 16, 12, 9, 6, 2])

In [89]:
puz_graph

array([[ 0, 10,  9,  2, 13,  7, 11,  3, 11,  3,  6,  6,  3,  5,  5,  7],
       [10,  0,  3, 12,  6,  3,  4,  7,  2, 10, 13,  8, 11,  7,  5,  5],
       [ 9,  3,  0, 10,  4,  5,  2,  6,  2,  8, 11,  5,  8,  5,  4,  2],
       [ 2, 12, 10,  0, 14,  9, 12,  5, 12,  2,  5,  5,  2,  5,  7,  8],
       [13,  6,  4, 14,  0,  9,  2, 10,  4, 12, 15,  9, 12,  9,  8,  6],
       [ 7,  3,  5,  9,  9,  0,  7,  4,  5,  7, 10,  5,  8,  4,  2,  3],
       [11,  4,  2, 12,  2,  7,  0,  8,  2, 10, 13,  7, 10,  7,  6,  4],
       [ 3,  7,  6,  5, 10,  4,  8,  0,  8,  5,  8,  3,  6,  2,  2,  4],
       [11,  2,  2, 12,  4,  5,  2,  8,  0, 10, 13,  7, 10,  7,  6,  4],
       [ 3, 10,  8,  2, 12,  7, 10,  5, 10,  0,  3,  5,  3,  3,  5,  6],
       [ 6, 13, 11,  5, 15, 10, 13,  8, 13,  3,  0,  8,  6,  6,  8,  9],
       [ 6,  8,  5,  5,  9,  5,  7,  3,  7,  5,  8,  0,  3,  2,  3,  3],
       [ 3, 11,  8,  2, 12,  8, 10,  6, 10,  3,  6,  3,  0,  5,  6,  6],
       [ 5,  7,  5,  5,  9,  4,  7,  2,  7,  3,  6,